-- Florida First Roofing LLC - All 67 County SOPs
-- Generated: 2025-10-18T14:56:50.224Z

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8200',
    9,
    'ALACHUA COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Alachua County',
    'All Florida First Roofing operations within Alachua County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Alachua County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8200-ALACHUA-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8201',
    9,
    'BAKER COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Baker County',
    'All Florida First Roofing operations within Baker County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Baker County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8201-BAKER-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8202',
    9,
    'BAY COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Bay County',
    'All Florida First Roofing operations within Bay County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Bay County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8202-BAY-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8203',
    9,
    'BRADFORD COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Bradford County',
    'All Florida First Roofing operations within Bradford County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Bradford County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8203-BRADFORD-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8204',
    9,
    'BREVARD COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Brevard County',
    'All Florida First Roofing operations within Brevard County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Brevard County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8204-BREVARD-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8205',
    9,
    'BROWARD COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    1,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Broward County',
    'All Florida First Roofing operations within Broward County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Broward County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8205-BROWARD-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8206',
    9,
    'CALHOUN COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Calhoun County',
    'All Florida First Roofing operations within Calhoun County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Calhoun County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8206-CALHOUN-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8207',
    9,
    'CHARLOTTE COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Charlotte County',
    'All Florida First Roofing operations within Charlotte County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Charlotte County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8207-CHARLOTTE-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8208',
    9,
    'CITRUS COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Citrus County',
    'All Florida First Roofing operations within Citrus County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Citrus County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8208-CITRUS-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8209',
    9,
    'CLAY COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Clay County',
    'All Florida First Roofing operations within Clay County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Clay County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8209-CLAY-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8210',
    9,
    'COLLIER COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Collier County',
    'All Florida First Roofing operations within Collier County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Collier County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8210-COLLIER-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8211',
    9,
    'COLUMBIA COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Columbia County',
    'All Florida First Roofing operations within Columbia County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Columbia County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8211-COLUMBIA-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8212',
    9,
    'DESOTO COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within DeSoto County',
    'All Florida First Roofing operations within DeSoto County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'DeSoto County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8212-DESOTO-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8213',
    9,
    'DIXIE COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Dixie County',
    'All Florida First Roofing operations within Dixie County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Dixie County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8213-DIXIE-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8214',
    9,
    'DUVAL COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Duval County',
    'All Florida First Roofing operations within Duval County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Duval County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8214-DUVAL-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8215',
    9,
    'ESCAMBIA COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Escambia County',
    'All Florida First Roofing operations within Escambia County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Escambia County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8215-ESCAMBIA-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8216',
    9,
    'FLAGLER COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Flagler County',
    'All Florida First Roofing operations within Flagler County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Flagler County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8216-FLAGLER-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8217',
    9,
    'FRANKLIN COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Franklin County',
    'All Florida First Roofing operations within Franklin County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Franklin County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8217-FRANKLIN-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8218',
    9,
    'GADSDEN COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Gadsden County',
    'All Florida First Roofing operations within Gadsden County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Gadsden County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8218-GADSDEN-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8219',
    9,
    'GILCHRIST COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Gilchrist County',
    'All Florida First Roofing operations within Gilchrist County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Gilchrist County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8219-GILCHRIST-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8220',
    9,
    'GLADES COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Glades County',
    'All Florida First Roofing operations within Glades County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Glades County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8220-GLADES-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8221',
    9,
    'GULF COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Gulf County',
    'All Florida First Roofing operations within Gulf County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Gulf County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8221-GULF-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8222',
    9,
    'HAMILTON COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Hamilton County',
    'All Florida First Roofing operations within Hamilton County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Hamilton County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8222-HAMILTON-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8223',
    9,
    'HARDEE COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Hardee County',
    'All Florida First Roofing operations within Hardee County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Hardee County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8223-HARDEE-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8224',
    9,
    'HENDRY COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Hendry County',
    'All Florida First Roofing operations within Hendry County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Hendry County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8224-HENDRY-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8225',
    9,
    'HERNANDO COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Hernando County',
    'All Florida First Roofing operations within Hernando County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Hernando County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8225-HERNANDO-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8226',
    9,
    'HIGHLANDS COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Highlands County',
    'All Florida First Roofing operations within Highlands County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Highlands County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8226-HIGHLANDS-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8227',
    9,
    'HILLSBOROUGH COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Hillsborough County',
    'All Florida First Roofing operations within Hillsborough County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Hillsborough County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8227-HILLSBOROUGH-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8228',
    9,
    'HOLMES COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Holmes County',
    'All Florida First Roofing operations within Holmes County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Holmes County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8228-HOLMES-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8229',
    9,
    'INDIAN RIVER COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Indian River County',
    'All Florida First Roofing operations within Indian River County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Indian River County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8229-INDIAN RIVER-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8230',
    9,
    'JACKSON COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Jackson County',
    'All Florida First Roofing operations within Jackson County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Jackson County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8230-JACKSON-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8231',
    9,
    'JEFFERSON COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Jefferson County',
    'All Florida First Roofing operations within Jefferson County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Jefferson County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8231-JEFFERSON-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8232',
    9,
    'LAFAYETTE COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Lafayette County',
    'All Florida First Roofing operations within Lafayette County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Lafayette County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8232-LAFAYETTE-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8233',
    9,
    'LAKE COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Lake County',
    'All Florida First Roofing operations within Lake County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Lake County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8233-LAKE-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8234',
    9,
    'LEE COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Lee County',
    'All Florida First Roofing operations within Lee County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Lee County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8234-LEE-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8235',
    9,
    'LEON COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Leon County',
    'All Florida First Roofing operations within Leon County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Leon County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8235-LEON-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8236',
    9,
    'LEVY COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Levy County',
    'All Florida First Roofing operations within Levy County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Levy County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8236-LEVY-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8237',
    9,
    'LIBERTY COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Liberty County',
    'All Florida First Roofing operations within Liberty County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Liberty County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8237-LIBERTY-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8238',
    9,
    'MADISON COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Madison County',
    'All Florida First Roofing operations within Madison County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Madison County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8238-MADISON-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8239',
    9,
    'MANATEE COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Manatee County',
    'All Florida First Roofing operations within Manatee County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Manatee County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8239-MANATEE-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8240',
    9,
    'MARION COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Marion County',
    'All Florida First Roofing operations within Marion County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Marion County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8240-MARION-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8241',
    9,
    'MARTIN COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    1,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Martin County',
    'All Florida First Roofing operations within Martin County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Martin County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8241-MARTIN-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8242',
    9,
    'MIAMI-DADE COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    1,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Miami-Dade County',
    'All Florida First Roofing operations within Miami-Dade County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Miami-Dade County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8242-MIAMI-DADE-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8243',
    9,
    'MONROE COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    1,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Monroe County',
    'All Florida First Roofing operations within Monroe County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Monroe County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8243-MONROE-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8244',
    9,
    'NASSAU COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Nassau County',
    'All Florida First Roofing operations within Nassau County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Nassau County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8244-NASSAU-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8245',
    9,
    'OKALOOSA COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Okaloosa County',
    'All Florida First Roofing operations within Okaloosa County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Okaloosa County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8245-OKALOOSA-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8246',
    9,
    'OKEECHOBEE COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Okeechobee County',
    'All Florida First Roofing operations within Okeechobee County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Okeechobee County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8246-OKEECHOBEE-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8247',
    9,
    'ORANGE COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Orange County',
    'All Florida First Roofing operations within Orange County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Orange County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8247-ORANGE-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8248',
    9,
    'OSCEOLA COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Osceola County',
    'All Florida First Roofing operations within Osceola County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Osceola County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8248-OSCEOLA-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8249',
    9,
    'PALM BEACH COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    1,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Palm Beach County',
    'All Florida First Roofing operations within Palm Beach County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Palm Beach County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8249-PALM BEACH-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8250',
    9,
    'PASCO COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Pasco County',
    'All Florida First Roofing operations within Pasco County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Pasco County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8250-PASCO-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8251',
    9,
    'PINELLAS COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Pinellas County',
    'All Florida First Roofing operations within Pinellas County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Pinellas County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8251-PINELLAS-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8252',
    9,
    'POLK COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Polk County',
    'All Florida First Roofing operations within Polk County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Polk County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8252-POLK-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8253',
    9,
    'PUTNAM COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Putnam County',
    'All Florida First Roofing operations within Putnam County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Putnam County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8253-PUTNAM-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8254',
    9,
    'SANTA ROSA COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Santa Rosa County',
    'All Florida First Roofing operations within Santa Rosa County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Santa Rosa County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8254-SANTA ROSA-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8255',
    9,
    'SARASOTA COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Sarasota County',
    'All Florida First Roofing operations within Sarasota County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Sarasota County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8255-SARASOTA-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8256',
    9,
    'SEMINOLE COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Seminole County',
    'All Florida First Roofing operations within Seminole County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Seminole County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8256-SEMINOLE-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8257',
    9,
    'ST. JOHNS COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within St. Johns County',
    'All Florida First Roofing operations within St. Johns County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'St. Johns County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8257-ST. JOHNS-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8258',
    9,
    'ST. LUCIE COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    1,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within St. Lucie County',
    'All Florida First Roofing operations within St. Lucie County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'St. Lucie County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8258-ST. LUCIE-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8259',
    9,
    'SUMTER COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Sumter County',
    'All Florida First Roofing operations within Sumter County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Sumter County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8259-SUMTER-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8260',
    9,
    'SUWANNEE COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Suwannee County',
    'All Florida First Roofing operations within Suwannee County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Suwannee County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8260-SUWANNEE-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8261',
    9,
    'TAYLOR COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Taylor County',
    'All Florida First Roofing operations within Taylor County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Taylor County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8261-TAYLOR-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8262',
    9,
    'UNION COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Union County',
    'All Florida First Roofing operations within Union County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Union County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8262-UNION-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8263',
    9,
    'VOLUSIA COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Volusia County',
    'All Florida First Roofing operations within Volusia County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Volusia County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8263-VOLUSIA-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8264',
    9,
    'WAKULLA COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Wakulla County',
    'All Florida First Roofing operations within Wakulla County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Wakulla County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8264-WAKULLA-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8265',
    9,
    'WALTON COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Walton County',
    'All Florida First Roofing operations within Walton County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Walton County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8265-WALTON-COUNTY-OPERATIONS.md'
  );

INSERT INTO sop_procedures (
    sop_number,
    category_id,
    title,
    version,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    purpose,
    scope,
    procedure_steps,
    safety_requirements,
    estimated_duration_minutes,
    created_by,
    approval_date,
    effective_date,
    review_date,
    next_review_date,
    content_file_path
  ) VALUES (
    '8266',
    9,
    'WASHINGTON COUNTY OPERATIONS',
    '2025.10',
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    'To establish comprehensive operational procedures for Florida First Roofing LLC operations within Washington County',
    'All Florida First Roofing operations within Washington County boundaries',
    '["Pre-Project Planning and Permits","Project Execution and Compliance","Project Completion and Follow-up"]',
    'Washington County specific safety requirements and emergency procedures',
    240,
    'County Operations Generator',
    '2025-10-18',
    '2025-10-18',
    '2025-10-18',
    '2026-01-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8266-WASHINGTON-COUNTY-OPERATIONS.md'
  );