INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8200',
    'ALACHUA COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Alachua County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8200-ALACHUA-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8201',
    'BAKER COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Baker County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8201-BAKER-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8202',
    'BAY COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Bay County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8202-BAY-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8203',
    'BRADFORD COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Bradford County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8203-BRADFORD-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8204',
    'BREVARD COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Brevard County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8204-BREVARD-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8205',
    'BROWARD COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Broward County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    1,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8205-BROWARD-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8206',
    'CALHOUN COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Calhoun County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8206-CALHOUN-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8207',
    'CHARLOTTE COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Charlotte County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    1,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8207-CHARLOTTE-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8208',
    'CITRUS COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Citrus County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8208-CITRUS-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8209',
    'CLAY COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Clay County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8209-CLAY-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8210',
    'COLLIER COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Collier County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    1,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8210-COLLIER-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8211',
    'COLUMBIA COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Columbia County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8211-COLUMBIA-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8212',
    'DESOTO COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within DeSoto County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8212-DESOTO-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8213',
    'DIXIE COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Dixie County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8213-DIXIE-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8214',
    'DUVAL COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Duval County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8214-DUVAL-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8215',
    'ESCAMBIA COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Escambia County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8215-ESCAMBIA-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8216',
    'FLAGLER COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Flagler County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8216-FLAGLER-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8217',
    'FRANKLIN COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Franklin County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8217-FRANKLIN-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8218',
    'GADSDEN COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Gadsden County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8218-GADSDEN-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8219',
    'GILCHRIST COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Gilchrist County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8219-GILCHRIST-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8220',
    'GLADES COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Glades County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8220-GLADES-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8221',
    'GULF COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Gulf County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8221-GULF-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8222',
    'HAMILTON COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Hamilton County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8222-HAMILTON-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8223',
    'HARDEE COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Hardee County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8223-HARDEE-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8224',
    'HENDRY COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Hendry County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8224-HENDRY-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8225',
    'HERNANDO COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Hernando County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8225-HERNANDO-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8226',
    'HIGHLANDS COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Highlands County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8226-HIGHLANDS-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8227',
    'HILLSBOROUGH COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Hillsborough County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8227-HILLSBOROUGH-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8228',
    'HOLMES COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Holmes County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8228-HOLMES-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8229',
    'INDIAN RIVER COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Indian River County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8229-INDIAN RIVER-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8230',
    'JACKSON COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Jackson County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8230-JACKSON-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8231',
    'JEFFERSON COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Jefferson County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8231-JEFFERSON-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8232',
    'LAFAYETTE COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Lafayette County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8232-LAFAYETTE-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8233',
    'LAKE COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Lake County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8233-LAKE-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8234',
    'LEE COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Lee County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    1,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8234-LEE-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8235',
    'LEON COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Leon County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8235-LEON-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8236',
    'LEVY COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Levy County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8236-LEVY-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8237',
    'LIBERTY COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Liberty County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8237-LIBERTY-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8238',
    'MADISON COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Madison County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8238-MADISON-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8239',
    'MANATEE COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Manatee County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8239-MANATEE-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8240',
    'MARION COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Marion County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8240-MARION-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8241',
    'MARTIN COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Martin County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    1,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8241-MARTIN-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8242',
    'MIAMI-DADE COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Miami-Dade County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    1,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8242-MIAMI-DADE-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8243',
    'MONROE COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Monroe County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    1,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8243-MONROE-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8244',
    'NASSAU COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Nassau County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8244-NASSAU-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8245',
    'OKALOOSA COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Okaloosa County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8245-OKALOOSA-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8246',
    'OKEECHOBEE COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Okeechobee County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8246-OKEECHOBEE-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8247',
    'ORANGE COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Orange County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8247-ORANGE-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8248',
    'OSCEOLA COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Osceola County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8248-OSCEOLA-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8249',
    'PALM BEACH COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Palm Beach County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    1,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8249-PALM BEACH-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8250',
    'PASCO COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Pasco County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8250-PASCO-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8251',
    'PINELLAS COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Pinellas County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8251-PINELLAS-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8252',
    'POLK COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Polk County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8252-POLK-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8253',
    'PUTNAM COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Putnam County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8253-PUTNAM-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8254',
    'SANTA ROSA COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Santa Rosa County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8254-SANTA ROSA-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8255',
    'SARASOTA COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Sarasota County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    1,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8255-SARASOTA-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8256',
    'SEMINOLE COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Seminole County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8256-SEMINOLE-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8257',
    'ST. JOHNS COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within St. Johns County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8257-ST. JOHNS-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8258',
    'ST. LUCIE COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within St. Lucie County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    1,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8258-ST. LUCIE-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8259',
    'SUMTER COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Sumter County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8259-SUMTER-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8260',
    'SUWANNEE COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Suwannee County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8260-SUWANNEE-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8261',
    'TAYLOR COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Taylor County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8261-TAYLOR-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8262',
    'UNION COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Union County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8262-UNION-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8263',
    'VOLUSIA COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Volusia County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8263-VOLUSIA-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8264',
    'WAKULLA COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Wakulla County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8264-WAKULLA-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8265',
    'WALTON COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Walton County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8265-WALTON-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );

INSERT INTO sop_procedures (
    sop_number,
    title,
    description,
    category_id,
    status,
    priority_level,
    compliance_required,
    florida_specific,
    hurricane_related,
    osha_related,
    hvhz_related,
    estimated_duration_minutes,
    version,
    effective_date,
    review_date,
    content_file_path,
    created_by,
    updated_by
  ) VALUES (
    '8266',
    'WASHINGTON COUNTY OPERATIONS',
    'Comprehensive operational procedures for Florida First Roofing LLC operations within Washington County, ensuring full compliance with local building codes, permit requirements, environmental regulations, and emergency protocols.',
    8,
    'active',
    'high',
    1,
    1,
    1,
    1,
    0,
    240,
    '2025.10',
    '2025-10-18',
    '2026-10-18',
    'SOPs/8000-Regulatory-Compliance/County-Specific/SOP-8266-WASHINGTON-COUNTY-OPERATIONS.md',
    'Winston Johnson',
    'Winston Johnson'
  );